"use strict";(()=>{Logger.info("Gmail content script loading...");let c={},k=!1,g=null;function u(){g&&clearTimeout(g),g=setTimeout(()=>{v(),d()},100)}function h(){Logger.info("Initializing..."),T(),m(),window.addEventListener("cu-task-created",t=>{const{task:e,threadId:i}=t.detail;D(i,e)})}async function m(){try{const e=(await chrome.storage.local.get("emailTaskMappings")).emailTaskMappings||{},i=Object.keys(e);i.length>0&&Logger.debug("Loaded linked tasks:",i),k||(k=!0,y(e)),c=e,d()}catch{c={}}}async function y(t){Logger.info(" Validating tasks (one-time check)...");let e=!1;for(const i of Object.keys(t)){const a=t[i];if(!Array.isArray(a))continue;const n=[];for(const o of a)try{const s=await chrome.runtime.sendMessage({action:"validateTask",taskId:o.id}),l=(s?.error||"").toLowerCase(),r=l.includes("not found")||l.includes("deleted");s&&s.exists&&!r?n.push(o):(e=!0,Logger.info(" Removed deleted task:",o.id))}catch{n.push(o)}n.length!==a.length&&(t[i]=n)}e&&(await chrome.storage.local.set({emailTaskMappings:t}),c=t,L())}function L(){document.querySelectorAll(".cu-email-bar").forEach(t=>{const e=t.dataset.threadId||"",i=c[e]||[],a=t.querySelector(".cu-linked-tasks");a&&(a.innerHTML=i.map(n=>`
                <a href="${n.url}" target="_blank" class="cu-task-link">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="#7B68EE">
                        <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
                    </svg>
                    ${f(n.name)}
                </a>
            `).join(""))})}function T(){Logger.debug("Starting MutationObserver..."),new MutationObserver(()=>{requestAnimationFrame(u)}).observe(document.body,{childList:!0,subtree:!0}),v(),d()}function v(){const t=GmailAdapter.getAllEmailBodies();t.length>0&&Logger.debug(`ScanEmails: found ${t.length} email bodies`),t.forEach(e=>{const i=e.closest(".gs")||e.closest(".h7")||e.parentElement;if(!i)return;const a=i.querySelector(".cu-email-bar");if(a){const o=parseInt(a.dataset.createdAt||"0"),s=Date.now()-o;if(s<3e4)return;Logger.info(` Refreshing stale bar. Age: ${Math.round(s/1e3)}s`),a.remove()}const n=M();Logger.info(" Injecting bar for thread:",n),A(i,e,n)})}function d(){document.querySelectorAll("tr.zA").forEach(e=>{const i=e.querySelector("[data-legacy-thread-id]");if(!i)return;const a=i.getAttribute("data-legacy-thread-id");if(!a||e.querySelector(".cu-inbox-task-badge"))return;let n=c[a]||c["email_"+a];if(!n){for(const[o,s]of Object.entries(c))if(o.includes(a)){n=s;break}}if(n&&n.length>0){const o=e.querySelector(".bqe")||e.querySelector(".bog span")||e.querySelector(".y6 span"),s=e.querySelector("td.xY")||e.querySelector("td.a4W"),l=document.createElement("span");if(l.className="cu-inbox-task-badge",l.title=`ClickUp: ${n.map(r=>r.name).join(", ")}`,l.style.cssText="display: inline-flex; margin-right: 6px; vertical-align: middle;",n.length===1){const r=document.createElement("a");r.href=n[0].url,r.target="_blank",r.className="cu-inbox-task-link",r.textContent="#"+n[0].id,r.addEventListener("click",p=>{p.stopPropagation(),p.preventDefault(),window.open(n[0].url,"_blank")}),l.appendChild(r)}else{const r=document.createElement("span");r.className="cu-inbox-task-count",r.textContent=n.length+" tasks",l.appendChild(r)}if(o?.parentElement)o.parentElement.insertBefore(l,o),Logger.info(" Added inbox badge for:",a);else if(s){const r=s.querySelector(".y6")||s.firstChild;r?.parentElement&&(r.parentElement.insertBefore(l,r),Logger.info(" Added inbox badge (fallback) for:",a))}}})}function M(){const t=GmailAdapter.getThreadId();return Logger.debug("Thread ID:",t),t}function w(){return GmailAdapter.getSubject()}function C(){return GmailAdapter.getSenderEmail()}function S(){return GmailAdapter.getEmailBodyHtml()}function A(t,e,i){const a=document.createElement("div");a.className="cu-email-bar",a.dataset.threadId=i,a.dataset.createdAt=Date.now().toString(),Logger.debug(` Injecting bar for thread: ${i}`,{tasks:c[i]});const n=c[i]||[];a.innerHTML=`
    <div class="cu-bar-content">
      <button class="cu-add-btn" title="Create ClickUp task from this email">
        <svg width="16" height="16" viewBox="0 0 180 180" fill="currentColor">
          <path d="M25.4 129.1L49.2 110.9C61.9 127.4 75.3 135 90.3 135C105.1 135 118.2 127.5 130.3 111.1L154.4 128.9C137 152.5 115.3 165 90.3 165C65.3 165 43.4 152.6 25.4 129.1Z"/>
          <polygon points="90.2 49.8 47.8 86.4 28.2 63.6 90.3 10.2 151.8 63.7 132.2 86.3"/>
        </svg>
        Add to ClickUp
      </button>
      <div class="cu-linked-tasks">
        ${E(n)}
      </div>
    </div>
    `,a.querySelector(".cu-add-btn")?.addEventListener("click",async s=>{s.preventDefault(),q(i)}),e.parentElement?.insertBefore(a,e),Logger.info(" Bar injected"),x(i,a)}function E(t){return!t||t.length===0?"":t.map(e=>`
        <a href="${e.url}" target="_blank" class="cu-task-link">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="#7B68EE">
            <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
          </svg>
          ${f(e.name)}
        </a>
    `).join("")}async function x(t,e){const i=c[t]||[];if(i.length===0)return;let a=!1;const n=[];for(const o of i)try{Logger.debug(" Verifying task:",o.id);const s=await chrome.runtime.sendMessage({action:"validateTask",taskId:o.id});Logger.debug(` Validation response for ${o.id}:`,s);const l=(s?.error||"").toLowerCase(),r=l.includes("not found")||l.includes("deleted");s&&s.exists&&!r?n.push(o):(Logger.info(" Detected deleted/archived task:",o.id),a=!0)}catch{n.push(o)}if(a){Logger.info(" Updating thread tasks after validation"),c[t]=n;const s=(await chrome.storage.local.get("emailTaskMappings")).emailTaskMappings||{};s[t]=n,await chrome.storage.local.set({emailTaskMappings:s});const l=e.querySelector(".cu-linked-tasks");l&&(l.innerHTML=E(n))}}function q(t){const e={threadId:t,subject:w(),from:C(),html:S()};typeof TaskModal<"u"?new TaskModal().show(e):(console.error("[ClickUp Task Tracker] TaskModal not found"),j("Error: Modal not loaded","error"))}function D(t,e){const i=document.querySelector(`.cu-email-bar[data-thread-id="${t}"]`);if(!i)return;const a=i.querySelector(".cu-linked-tasks"),n=document.createElement("a");n.href=e.url,n.target="_blank",n.className="cu-task-link cu-task-new",n.innerHTML=`
    <svg width="12" height="12" viewBox="0 0 24 24" fill="#7B68EE">
      <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
    </svg>
    ${f(e.name)}
    `,a?.appendChild(n),c[t]||(c[t]=[]),c[t].push({id:e.id,name:e.name,url:e.url})}function f(t){const e=document.createElement("div");return e.textContent=t,e.innerHTML}function j(t,e){const i=document.querySelector(".cu-notification");i&&i.remove();const a=document.createElement("div");a.className=`cu-notification cu-notification-${e}`,a.textContent=t,document.body.appendChild(a),setTimeout(()=>a.remove(),3e3)}let b="";window.addEventListener("popstate",()=>{Logger.info(" Navigation detected (popstate)"),m(),u()});setInterval(()=>{window.location.href!==b&&(b=window.location.href,Logger.info(" URL changed, reloading tasks..."),m(),u())},1e3);setInterval(()=>{d()},5e3);document.readyState==="loading"?document.addEventListener("DOMContentLoaded",h):h();})();
